### ISSUE TITLE
Add E2E testings

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#104]
**Improvement:**

It's necessary to add E2E testings to help QA team to control the quality of Octopus.

**References:**

- Check the test plan of PR https://github.com/cnrancher/octopus/pull/81.
- Check the test plan of PR https://github.com/cnrancher/octopus/pull/103.
- Verify the reproduced steps of https://github.com/cnrancher/octopus/issues/106.
- Based on the BDD framework, it's better to reuse what we did on Integration testing.
- No Python(Python is good, but I don't want to introduce another "NEW" thing.).

**Related Issues:**

**Todos:**
- [x] In the first phase, give an entrance script to start the E2E testing with a few test cases on an existing cluster.
- [ ] In the second phase, it needs to improve the E2E cases for adaptors:
   + [x] dummy, https://github.com/cnrancher/octopus/pull/130
   + [x] mqtt, https://github.com/cnrancher/octopus/pull/138
   + [ ] modbus
   + [ ] opcua
   + [ ] ble
- [ ] In the third phase, it should be able to create a remote cluster before testing.
- [ ] In the last phase, it should be able to integrate with CI when creating a new tag.
