### ISSUE TITLE
Unify MQTT extension and MQTT adaptor

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#115]
**Improvement:**

At present, the public libs of MQTT adaptor and MQTT extension are not reusable, we need to unify them.

**References:**

1. There is a deadlock issue in paho vendor, it needs to bump to master.
1. In MQTT extension configuration, we can move`will` message field into `message`, and keep the input content Base64-encoded always.
1. Preconfigure `qos=1` and `retained=true`.
1. Templated `topic` item to support a wider range of scenarios.
1. MQTT adaptor should only support two different scenarios: `AttributedTopic` and `AttributedMessage`, in `AttributedMessage` only support JSON-encoded at now.

**Related Issues:**

**Todos:**
- [x] Bump paho client
- [x] Adjust MQTT extension
- [x] Adjust MQTT adaptor
