### ISSUE TITLE
Normalize the fields naming in adaptor devices

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#118]
**Improvement:**

In the CRD of the device, there are many non-standard fields that we need to adjust.

**References:**

- DummySpecialDevice
```diff json
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
...
spec:
  ...
  template:
    ...
    spec:
      ...
-     props:
+     properties:
        ...
        gender:
          type: object
          description: "The gender of the robot."
-         objectProps:
+         objectProperties:
            name:
              type: string
              description: "The name of the gender."
            ...
        friends:
          type: array
          description: "The name list of the robot's friends."
-         arrayProps:
+         arrayProperties:
            type: string
            description: "The name of the friend."
        power:
          type: float
          description: "The power of the robot."
``` 

- ModbusDevice TCP
```diff json
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
...
spec:
  ...
  template:
    ...
    spec:
      ...
      protocol:
        tcp:
-         ip: 192.168.1.3
-         port: 502
+         endpoint: 192.168.1.3:5020
-         slaveID: 1
+         workerID: 1
      properties:
        - name: temperature-enable
          description: enable data collection of temperature sensor
          readOnly: false
          visitor:
            register: CoilRegister
            offset: 2
            quantity: 1
          value: "true"
-         dataType: boolean
+         type: boolean
```

- ModbusDevice RTU
```diff json
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
...
spec:
    ...
  template:
    ...
    spec:
      ...
      protocol:
        rtu:
-         serialPort: /dev/tty.usbserial-1410
+         endpoint: /dev/tty.usbserial-1410
-         slaveID: 1
+         workerID: 1
          parity: "N"
          stopBits: 1
          dataBits: 8
          baudRate: 9600
      properties:
        - name: temperature
          description: data collection of temperature sensor
          readOnly: true
          visitor:
            register: HoldingRegister
            offset: 0
            quantity: 1
            orderOfOperations:
-             - operationType: Divide
+             - type: Divide
-               operationValue: "10"
+               value: "10"
-         dataType: float
+         type: float

```

- OPCUADevice

```diff json
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
...
spec:
  ...
  template:
    ...
    spec:
      ...
      protocol:
-       url: opc.tcp://10.0.2.2:53530/OPCUA/SimulationServer
+       endpoint: opc.tcp://10.0.2.2:53530/OPCUA/SimulationServer
-       username: dadmin
-       password: admin
+       basicAuth:
+         username: dadmin
+         usernameRef:
+           name:
+           item:
+         password: admin
+         passwordRef:
+           name:
+           item:
-       certificateFile: ""
-       privateKeyFile: ""
+       tlsConfig:
+         certFilePEM:
+         certFilePEMRef:
+           name:
+           item:
+         keyFilePEM:
+         keyFilePEMRef:
+           name:
+           item:
      properties:
        - name: counter
          description: enable data collection of temperature sensor
          readOnly: true
          visitor:
            nodeID: ns=3;s=Counter
-         dataType: int32
+         type: int32
```

- BluetoothDevice
``` diff json
apiVersion: edge.cattle.io/v1alpha1
kind: DeviceLink
...
spec:
  ...
  template:
    ...
    spec:
      ...
      protocol:
-       name: "MJ_HT_V1"
-       macAddress: ""
+       endpoint: "MJ_HT_V1"
      properties:
        - name: data
          description: XiaoMi temp sensor with temperature and humidity data
          accessMode: NotifyOnly
          visitor:
            characteristicUUID: 226c000064764566756266734470666d
        - name: humidity
          description: Humidity in percent
          accessMode: ReadOnly
          visitor:
            characteristicUUID: f000aa0304514000b000000000000000
            # dataConverter is optional
            dataConverter:
              startIndex: 1
              endIndex: 0
              shiftRight: 2
              orderOfOperations:
-               - operationType: Multiply # options are Add/Subtract/Multiply/Divide
+               - type: Multiply # options are Add/Subtract/Multiply/Divide
-                 operationValue: "0.03125"
+                 value: "0.03125"
```

**Related Issues:**

**Todos:**
- [x] Clarify BLE adaptor
- [x] Clarify Modbus adaptor
- [x] Clarify OPC-UA adaptor
- [x] Nice to have, remove deprecated parameters `Parameters` from limb-adaptor grpc

**Comment by thxCode** [comment]
Close in favor of https://github.com/cnrancher/octopus/pull/120
