### ISSUE TITLE
Brief about the adaptor simulators

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#124]
**Improvement:**

We should give a brief about how to test with the [adaptor simulator](https://github.com/cnrancher/octopus-simulator).

**References:**

- Brief simulator usage in README
- Adjust adaptor E2E deployment YAML

**Related Issues:**

**Todos:**
- [x] Adjust Modbus E2E deployment YAML
- [x] Adjust MQTT E2E deployment YAML
- [x] Adjust OPC-UA E2E deployment YAML
