### ISSUE TITLE
Optimize the BLE adaptor

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#146]
**Improvement:**

1. We should find a solution to reduce the complexity of the BLE device, I got inspiration from [LightBlue](https://punchthrough.com/lightblue/), I think we can introduce a type system to provide a more friendly way of interaction.
1. The existing access model cannot handle those write-only GATT characteristics, and some GATT characteristics only need to be read once.
1. We suggest each characteristic UUID should be unique in practice, but it's still working when different GATT services have the same UUID GATT characteristic. So the existing visitor may not find the target characteristic if we only specify a 16-bits characteristic UUID.

**References:**

1. Introduce the type system like what we did at https://github.com/cnrancher/octopus/pull/145.
1. Enrich the access mode to handle more scenarios.
1. Support to build/test in Mac(darwin).
1. Support to find a GATT characteristic via service and characteristic UUIDs.

**Related Issues:**

https://github.com/cnrancher/octopus/issues/139

**Todos:**

- [x] Support to define the `type` of property.
- [x] Support to define the GATT service UUID and endianness in the `visitor` of property.
- [x] Remove the data converter from the property.
- [x] Enrich the access mode of property.
