### ISSUE TITLE
Optimize the Modbus adaptor

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#152]
**Improvement:**

1. Enrich the type of property.
1. The existing access model cannot handle those write-only registers, and some registers only need to be read once.
1. Both `parameters` and `protocol` are used to process the connection and should not be split into two fields.

**References:**

1. Add new types:
    
    - `float32` is as same as `float`.
    - `float64` is as same as `double`.
    - `binaryString` and `base64String` for simplifying the representation of `hexString`.

1. Introduce a new field `accessModes` to handle more scenarios.
1. Merge `parameter` and `protocol` together.

**Related Issues:**

**Todos:**
- [x] Add new types.
- [x] Introduce the `accessModes` of property.
- [x] Merge `parameters` into `protocol`.
