### ISSUE TITLE
Optimize the OPC-UA adaptor

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#154]
**Improvement:**

1. Enrich the type of property.
1. The existing access model cannot handle those write-only registers, and some registers only need to be read once.
1. Both `parameters` and `protocol` are used to process the connection and should not be split into two fields.
1. Support arithmetic operations in collected value.

**References:**

1. Adjust types:
    
    - add `float32` is as same as `float`.
    - add `float64` is as same as `double`.
    - add `binaryString`, `hexString`, `base64String` for simplifying the representation of `byteString`, and remove `byteString`.
    - add `int8` and `uint8`.
    - remove `datetime`.

1. Introduce a new field `accessModes` to handle more scenarios.
1. Merge `parameter` and `protocol` together.
1. Enrich client authentication modes in `protocol`.

**Related Issues:**

**Todos:**
- [x] Adjust new types.
- [x] Introduce the `accessModes` of property.
- [x] Merge `parameters` into `protocol` and enrich `protocol`.
