### ISSUE TITLE
Support log parameterization in adaptors

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#94]
**Improvement:**

It's better to parameterize the log of all adaptors.

**References:**

- Provide a logr log implementation.
- Parameterize all adaptors.

**Related Issues:**

**Todos:**
- [x] Implement a logr util based on zap.
- [x] Adjust the log parameters entrance of `brain` and `limb`.
- [x] Add a log parameters entrance for all adaptors.
