### ISSUE TITLE
Remove admission webhooks 

### ISSUE THREAD

**Issue by thxCode** [cnrancher/octopus#99]
**Improvement:**

There are not scenarios of DeviceLink admission webhooks, we can temporarily remove it.

**References:**

Remove all things about admission webhooks.

**Related Issues:**

**Todos:**
- [x] Use a commit to tweak the `all_in_one_without_webhook` to `all_in_one`.
- [x] Use another commit to remove all things about admission webhooks.
- [x] Adjust the related docs.
